version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - db_data:/app/site.db  # Mount the volume to persist the SQLite file
    # Remove the database service as we are managing the file within the app container

volumes:
  db_data: